contact_links:
  - name: 🤔 Support Question
    url: https://start9.com
    about: This issue tracker is not for support questions. Please post your question in our Telegram community channel, or go to Start9.com to speak with a live chat technician during most Western Hemisphere daylight hours.
